local CraftingSortInfo = {
  CategorySortOrder = {
    "Faction",
    "CraftingQuestRecipe",
    "CutStone",
    "RefinedResources",
    "Weapons",
    "Armor",
    "DungeonReplicas",
    "Ammo",
    "Tools",
    "Bags",
    "CutGems",
    "FuseGems",
    "MaterialConversion",
    "Trinkets",
    "BasicCooking",
    "Foods",
    "Consumables",
    "CraftingConsumables",
    "Components",
    "Concoctions",
    "ArcanaRefining",
    "CraftModRefining",
    "Dyes",
    "ResourceDowngrade",
    "Furniture"
  },
  GroupSortOrder = {
    "PvPStatSwap",
    "MundaneMetal",
    "PreciousMetal",
    "Charcoal",
    "Leather",
    "Cloth",
    "Planks",
    "Blocks",
    "CutGemsT1",
    "CutGemsT2",
    "CutGemsT3",
    "CutGemsT4",
    "CutGemsFuseT1",
    "CutGemsFuseT2",
    "CutGemsFuseT3",
    "CutGemsFuseT4",
    "Amulets",
    "Rings",
    "Earrings",
    "GemstoneDust",
    "MeleeWeapons",
    "MagicStaves",
    "RangedWeapons",
    "DungeonReps1",
    "DungeonReps2",
    "DungeonReps3",
    "DungeonReps4",
    "DungeonReps5",
    "DungeonReps6",
    "DungeonReps7",
    "DungeonReps8",
    "DungeonReps9",
    "DungeonReps10",
    "CraftingConsumables",
    "SurvivalTools",
    "ToolsGathering",
    "Ammo",
    "EngineeringComponents",
    "ArmorCloth",
    "ArmorRobe",
    "ArmorLeather",
    "ArmorFur",
    "ArmorPlate",
    "ArmorPlateHeavy",
    "Shields",
    "BagsGeneral",
    "Potion",
    "Coatings",
    "ConsumablesResistance",
    "ElementalWisp",
    "ElementalEssence",
    "ElementalQuintessence",
    "ModsUncommon",
    "ModsRare",
    "ModsEpic",
    "Conversion3",
    "Conversion4",
    "Conversion5",
    "FoodRecovery",
    "FoodComponents",
    "FoodSTR",
    "FoodDEX",
    "FoodINT",
    "FoodFOC",
    "FoodCON",
    "FoodTradeskill",
    "DyeWhite",
    "DyeGrey",
    "DyeBrown",
    "DyeRed",
    "DyeOrange",
    "DyeYellow",
    "DyeGreen",
    "DyeTurquoise",
    "DyeCyan",
    "DyeBlue",
    "DyeViolet",
    "DyeMagenta",
    "DyePurple",
    "WorkOrder",
    "SmallFurnishings",
    "LargeFurnishings",
    "Seating",
    "Storage",
    "Decorations",
    "Trophies",
    "RepairKits"
  },
  CategoryPriorityOrder = {},
  GroupPriorityOrder = {},
  initialized = false
}
function CraftingSortInfo:Initialize()
  if not self.initialized then
    self.initialized = true
    self.CategoryPriorityOrder = {}
    self.GroupPriorityOrder = {}
    for index, category in ipairs(self.CategorySortOrder) do
      self.CategoryPriorityOrder[category] = index
    end
    for index, group in ipairs(self.GroupSortOrder) do
      self.GroupPriorityOrder[group] = index
    end
  end
end
return CraftingSortInfo
